# Generated by Django 4.1.3 on 2022-12-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
